### PR TITLE
improve about reload message&use ${project.version}

### PR DESCRIPTION
**Pull request by YuanYuanOwO**
* Bump Spigot-API to 1.18.2,cause QuickShop-Hikari only support 1.18.2+(In fact, plans are underway to remove support for 1.18/1.19)  

Edit:enabled allow edits by maintainers,because I don't really understand how to resolve conflicts properly.

### CODE REVIEW

**Comment by BlvckBytes** [comment]
I have thought about collapsing missing-permission messages into a single generic version for a while now, but still think that it's making the user-experience worse, as one might not quite understand what's going on... Clicking on an item and just being told that they do not have permission, vs. being told that they cannot use filtering/sorting/teleport makes quite the difference, I believe. As for translation, these strings mostly only differ by a single word, so one can always copy and edit.

I'm happy to also employ `${project.version}` on this project - no remarks here.

As for the version, I do **not** want to update, just because the latest releases of `QuickShop-Hikari` do not support older versions. `QuickShopSearch` is not making use of any new Bukkit-API-features whatsoever, and `ItemPredicateParser` is inherently version-independent; so why would we not support older servers? This limitation seems artificial to me.

I hope you can understand my concerns; I really appreciate your suggestions, but I also have to try and stick to my long-term plans, which include as wide of a version-range as possible.

**Comment by YuanYuanOwO** [comment]
> I have thought about collapsing missing-permission messages into a single generic version for a while now, but still think that it's making the user-experience worse, as one might not quite understand what's going on... Clicking on an item and just being told that they do not have permission, vs. being told that they cannot use filtering/sorting/teleport makes quite the difference, I believe. As for translation, these strings mostly only differ by a single word, so one can always copy and edit.我已经考虑将缺少权限的消息折叠成一个通用版本有一段时间了，但仍然认为这会使用户体验变得更糟，因为人们可能不太明白发生了什么......单击一个项目并只是我相信，告诉他们没有权限，与告诉他们不能使用过滤/排序/传送有很大的不同。至于翻译，这些字符串大多只有一个单词不同，因此人们可以随时复制和编辑。
> 
> I'm happy to also employ `${project.version}` on this project - no remarks here.我很高兴还在这个项目上使用`${project.version}` - 这里没有任何评论。
> 
> As for the version, I do **not** want to update, just because the latest releases of `QuickShop-Hikari` do not support older versions. `QuickShopSearch` is not making use of any new Bukkit-API-features whatsoever, and `ItemPredicateParser` is inherently version-independent; so why would we not support older servers? This limitation seems artificial to me.至于版本，我**不想**更新，只是因为最新版本的`QuickShop-Hikari`不支持旧版本。 `QuickShopSearch`没有使用任何新的 Bukkit-API 功能，并且`ItemPredicateParser`本质上是版本无关的；那么我们为什么不支持旧服务器呢？这个限制对我来说似乎是人为的。
> 
> I hope you can understand my concerns; I really appreciate your suggestions, but I also have to try and stick to my long-term plans, which include as wide of a version-range as possible.希望您能理解我的担忧；我非常感谢您的建议，但我也必须尝试坚持我的长期计划，其中包括尽可能广泛的版本范围。



> I have thought about collapsing missing-permission messages into a single generic version for a while now, but still think that it's making the user-experience worse, as one might not quite understand what's going on... Clicking on an item and just being told that they do not have permission, vs. being told that they cannot use filtering/sorting/teleport makes quite the difference, I believe. As for translation, these strings mostly only differ by a single word, so one can always copy and edit.我已经考虑将缺少权限的消息折叠成一个通用版本有一段时间了，但仍然认为这会使用户体验变得更糟，因为人们可能不太明白发生了什么......单击一个项目并只是我相信，告诉他们没有权限，与告诉他们不能使用过滤/排序/传送有很大的不同。至于翻译，这些字符串大多只有一个单词不同，因此人们可以随时复制和编辑。
> 
> I'm happy to also employ `${project.version}` on this project - no remarks here.我很高兴还在这个项目上使用`${project.version}` - 这里没有任何评论。
> 
> As for the version, I do **not** want to update, just because the latest releases of `QuickShop-Hikari` do not support older versions. `QuickShopSearch` is not making use of any new Bukkit-API-features whatsoever, and `ItemPredicateParser` is inherently version-independent; so why would we not support older servers? This limitation seems artificial to me.至于版本，我**不想**更新，只是因为最新版本的`QuickShop-Hikari`不支持旧版本。 `QuickShopSearch`没有使用任何新的 Bukkit-API 功能，并且`ItemPredicateParser`本质上是版本无关的；那么我们为什么不支持旧服务器呢？这个限制对我来说似乎是人为的。
> 
> I hope you can understand my concerns; I really appreciate your suggestions, but I also have to try and stick to my long-term plans, which include as wide of a version-range as possible.希望您能理解我的担忧；我非常感谢您的建议，但我也必须尝试坚持我的长期计划，其中包括尽可能广泛的版本范围。

Ok, thanks for your reply!

But QuickShop-Hikari doesn't run after 1.18/1.19, does the plugin still load properly?

**Comment by BlvckBytes** [comment]
Do **all** versions of `QuickShop-Hikari` not load after 1.18, or are there older releases which do? No, without this dependency, the plugin does not load, as there would be no shops to query.

**Comment by YuanYuanOwO** [comment]
> Do **all** versions of `QuickShop-Hikari` not load before 1.18, or are there older releases which do? No, without this dependency, the plugin does not load, as there would be no shops to query.**所有**版本的`QuickShop-Hikari`是否在 1.18 之前都无法加载，或者是否有旧版本可以加载？不，如果没有这种依赖性，插件就不会加载，因为没有商店可供查询。

I think so, even though there are older versions that can be loaded prior to 1.18.2 that will break that dependent plugin due to API changes

```
Q: Hikari cannot load on 1.18(.0) and 1.18.1.
A: <1.18.2 have conficting issue with Adventure lib, upgrade to 1.18.2

Q: It cannot load on 1.7/1.8/1.9/1.10/1.11/1.12/1.13/1.14/1.15/1.16/1.17.
A: See "Tested Minecraft Versions", we only support 1.18(.2) and up.
```

**Comment by BlvckBytes** [comment]
Okay, I see - you're obviously far better informed than I am! :) I'll change my answer then; upgrading the API to `1.18.2` makes a lot of sense.

**Comment by YuanYuanOwO** [comment]
And then I don't know how to properly resolve the conflict.
Maybe I should revert the changes in plugin.yml and you add them back?

**Comment by BlvckBytes** [comment]
That's fine, I'll resolve the conflict.

**Pull request merged**
